before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.2-dev libboost-filesystem-dev libboost-filesystem-dev libboost-thread-dev
  - git clone git@github.com:mongodb/mongo-cxx-driver.git
  - cd mongo-cxx-driver && sudo scons --prefix=/usr install-mongoclient && cd -
  - wget https://github.com/moai/luamongo/archive/v0.4.1.tar.gz
  - tar zxvf v0.4.1.tar.gz
  - cd luamongo-0.4.1 && make && sudo cp mongo.so /usr/lib/lua/5.2 && cd -
  - ssh-kegen -b 2048 -t rsa -q -N ""
  - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
language: lua
script: ./test.sh
